### ISSUE TITLE
Syntax Error : BlockedScope declaration error

### ISSUE THREAD

**Issue by gabru-md** [yamboy1/terminal-utilities#5]
This can be resolved by adding: 
`"use strict";`
at the beginning!

cheers! thanks for the module!

**Comment by yamboy1** [comment]
Thanks for the I've added `'use_strict'`. See ae16aaf

By the way, what version of node.js are you using?

**Comment by yamboy1** [comment]
I've changed `'use_strict'` to `'use strict'`. See 284e7ab169b0718d2a6df003e58cb56

**Comment by gabru-md** [comment]
I'll have to check. Maybe it is because of difference in version.

**Comment by yamboy1** [comment]
@gabru-md Closing now because issue is fixed
